# Generated by Django 5.0.1 on 2024-01-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0009_user_alter_category_options_alter_women_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='is_published',
            field=models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, verbose_name='Статус'),
        ),
    ]
